#include <iostream>
#include <algorithm>
#include <string>
#include <fstream>
#include <sstream>
#include <chrono>
#include <vector>
#include <map>
#include <unordered_map>
#include <memory>
#include <glm-0.9.8.5\glm/glm.hpp>
#include <glm-0.9.8.5\glm/gtc/matrix_transform.hpp>
#include <glm-0.9.8.5\glm/gtc/type_ptr.hpp>
#include <glad\glad.h>
#include <GLFW\glfw3.h>
#include "stb_image.h"
#include <boost\functional\hash.hpp>
#include <boost\exception\diagnostic_information.hpp>